version: '3'
services:
  postgres:
    image: 'postgres'
    environment:
      POSTGRES_DB: pgclient_test
      POSTGRES_USER: pgclient_user
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - '5434:5432'
